# Setup
title:               Blogs
tagline:             'felladog'
description:         'Made with <a href="https://jekyllrb.com" target="_blank">Jekyll</a>,<a href="https://github.com/poole/lanyon" target="_blank">Lanyon</a> and Love.'
url:                 https://utsavdarlami.github.io/blogs/
baseurl:             '/blogs'
paginate:            7
permalink:           pretty
bio:                 ':q'
excerpt_separator:    <!--more-->

# About/contact
author:
  name:              Utsav Darlami 
  url:               https://github.com/utsavdarlami 
  email:             utsavdarlami17@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
