baseurl = "https://utsavdarlami.github.io/blogs/"
title = "felladog"
theme = "blank"
languageCode = "en"

paginate = 20

pygmentsCodeFences = true
pygmentsUseClasses = true

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL =  "/blogs/404.html"
ignoreErrors = ["error-remote-getjson"]




[Params]
title = "felladog blog"
subtitle = "felladog"
githubUrl = "https://github.com/utsavdarlami/"
homeUrl = "https://utsavdarlami.github.io/"
dlogUrl = "https://utsavdarlami.github.io/dlog/"
issueUrl = "https://github.com/utsavdarlami/blogs/issues/new"
author = "Utsav Darlami"
description = "felladog"
notoc = false 
mainsections = "posts"
# ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
