baseurl = "https://utsavdarlami.github.io/blogs/"
title = "felladog"
theme = "blank"
languageCode = "en"

paginate = 100

pygmentsCodeFences = true
pygmentsUseClasses = true


[Params]
title = "felladog blog"
subtitle = "felladog"
githubUrl = "https://github.com/utsavdarlami/"
homeUrl = "https://utsavdarlami.github.io/"
issueUrl = "https://github.com/utsavdarlami/blogs/issues/new"
author = "Utsav Darlami"
description = "felladog"
notoc = false 
# ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
